language: python
python:
  - 3.6
install:
  - pip install .
  - pip install pipenv
  - pipenv lock --clear
  - pipenv install --dev
  - pipenv graph # Missing Dependency? Why?
script:
  - pipenv run pytest
