language: python
python:
  - 2.7
  - 3.5
  - 3.6
install:
  - export BOTO_CONFIG=/dev/null
  - pip install .
  - pip install -r requirements-test.txt
script:
  - pytest

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
