[project]
name = "awswl"
version = "1.3.1"
description = "A project to make it simple to add/remove ip addresses (or CIDR blocks) from an AWS Security group."
authors = [
    { name = "Geoffrey Wiseman", email = "geoffrey.wiseman@codiform.com" }
]
license = "Unlicense"
license-files = ["LICENSE.txt"]
readme = "README.md"
keywords = ["aws", "vpn", "securitygroups", "security", "networking", "allowlist", "ssh", "firewall", "utility"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: System :: Networking",
    "Topic :: System :: Networking :: Firewalls",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14"
]
requires-python = ">=3.10,<4"
dependencies = [
    "ipaddress (>=1.0.23,<2)",
    "boto3 (>=1.35.62,<2)",
    "requests (==2.34.2)",
    "urllib3 (<3)"
]

[project.urls]
homepage = "https://github.com/geoffreywiseman/awswl"
repository = "https://github.com/geoffreywiseman/awswl"

[project.scripts]
awswl = "awswl.main:main"

[dependency-groups]
dev = [
    "pytest (>=8.4.2,<10.0.0)",
    "moto (>=5.0.0,<6)",
    "mock (>=5.1.0,<6)",
    "ruff (>=0.7.3,<0.17.0)"
]

[build-system]
requires = ["poetry-core>=2.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120
