#!/usr/bin/env bash
readonly ERR_RM=1
readonly ERR_SDIST=2
readonly ERR_WHEEL=3
readonly ERR_UL=4
readonly ERR_ABORT=5

readonly VERSION=$(cat awswl/VERSION)

release() {
  printf "Removing past distribution files from dist/.\\n\\n"
  if ! rm -v dist/* ; then
    printf "Couldn't remove past distribution files.\\n"
    exit $ERR_RM;
  fi

  printf "\\nCreating source distribution:\\n\\n"
  if ! python setup.py sdist; then
    printf "Couldn't create source distribution.\\n"
    exit $ERR_SDIST
  fi

  printf "\\nCreating universal wheel...\\n\\n"
  if ! python setup.py bdist_wheel --universal; then
    printf "Couldn't create universal wheel.\\n"
    exit $ERR_WHEEL
  fi

  printf "\\nUploading with twine...\\n\\n"
  if ! twine upload dist/*; then
    printf "Couldn't upload distribution files.\\n\\n"
    exit $ERR_UL
  fi

  printf "\\nRelease complete.\\n"
}

read -p "Release v$VERSION of awswl module? [yN]: " response
case $response in
  [Yy] | Yes | yes) release;;
  *) printf "Ok, aborting.\\n\\n"; exit $ERR_ABORT;;
esac
